color: red
fieldLayouts:
  4a7db94a-bd60-4fb0-8078-fa883173d225:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2ba58f3e-5fc7-48bb-95cc-204929aaaa18
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a45df4e-9a9d-4d13-9a73-62265aafe1d4 # Fotos
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ad6c0f3-e733-4d68-953a-627b5a9ab25f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 324648bc-f878-478b-804e-1e657b33c79d # aboutDescription
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: febfd7e0-ca35-4196-9339-6a5eba66b61d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 21132f38-dc04-4fe9-99d5-8059c030eb75
        userCondition: null
handle: about
hasTitleField: true
icon: user
name: About
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
