color: blue
fieldLayouts:
  0bf46b84-d688-4584-b5c2-0863d3e37e54:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0be1431f-c3d2-4ff0-bdbc-f88c62231252
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d47ddfe-72ec-4111-b1cd-3caa343d172b # Logo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c1e13ab-a927-4726-a034-0fa67104053a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 26288c94-7ffc-42ab-85b3-95f4f552f079 # showcaseTitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e300d89-5792-4fac-a648-8321d3141d3d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2c92eeaa-396b-4703-9978-22ba146e4d0c # errorMessage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96d191da-669a-46e6-a73f-8a674f45d663
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4ce23293-4586-4d8e-9876-87875f5e0434
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f71a819e-0877-407a-a17a-b82f88e5e2c0 # aboutTitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16045a11-9e46-4ffb-93da-063750c9eeda
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 324648bc-f878-478b-804e-1e657b33c79d # aboutDescription
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cbc5dbb-387b-4cb0-83f9-289befa4908e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a45df4e-9a9d-4d13-9a73-62265aafe1d4 # Fotos
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0547424-b863-414e-9d13-3a087d9e7f9a
            userCondition: null
            warning: null
            width: 100
        name: About
        uid: 74b98e76-aac4-43a2-bdeb-aa764eb7aff5
        userCondition: null
handle: home
hasTitleField: true
icon: house
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
