baseUrl: 'http://werkpakket3.ddev.site/nl'
enabled: '1'
handle: illustrashopnl
hasUrls: true
language: nl
name: IllustrashopNL
primary: false
siteGroup: b983c117-aebe-4dd5-92b8-5d0d49b48b82 # Illustrashop
sortOrder: 2
