columnSuffix: null
handle: newContent
instructions: 'Make your own content'
name: 'new Content'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - f7a67229-f99c-40e8-b985-7c7c3ed7d2c2 # newTextImage
    - 0c31d4c6-11c3-499d-846f-0326778ac5fe # newForm
    - db76d38d-3ae1-4c18-89cf-245e9b84df65 # newProductBlock
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
