columnSuffix: null
handle: phonenumber
instructions: null
name: phoneNumber
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: '0000 00 00 00'
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
