columnSuffix: null
handle: stickercard
instructions: null
name: stickerCard
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 3
  minRelations: 3
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:cfbedfb0-7790-41c9-a3cc-0f9f7cdb7227' # stickers
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
