dateModified: 1714655468
email:
  fromEmail: nathan.ddk@outlook.com
  fromName: Illustrashop
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: /images
meta:
  __names__:
    1d47ddfe-72ec-4111-b1cd-3caa343d172b: Logo # Logo
    4a826233-2673-4533-bdf4-5dd6f0487adc: Illustrashop # Illustrashop
    56a88afc-1100-4ee0-8f36-380a2e7fdc28: 'Public Schema' # Public Schema
    86945d3a-9e49-4245-b5cf-e27ed83e8f76: Images # Images
    347620c5-2d4f-42f5-8745-b16fff55dec6: Home # Home
    b983c117-aebe-4dd5-92b8-5d0d49b48b82: Illustrashop # Illustrashop
    dc56cc87-678f-4d74-a517-414aba78a3b2: About # About
    f353af18-96fc-4a3f-9c95-586303d02d2c: Home # Home
    fdb40e6b-86d1-45a0-9ff2-85269d1d1550: About # About
system:
  edition: solo
  live: true
  name: Illustrashop
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
