dateModified: 1714481380
email:
  fromEmail: nathan.ddk@outlook.com
  fromName: Illustrashop
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    4a826233-2673-4533-bdf4-5dd6f0487adc: Illustrashop # Illustrashop
    b983c117-aebe-4dd5-92b8-5d0d49b48b82: Illustrashop # Illustrashop
system:
  edition: solo
  live: true
  name: Illustrashop
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
