dateModified: 1715690473
email:
  fromEmail: nathan.ddk@outlook.com
  fromName: Illustrashop
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: /images
meta:
  __names__:
    0c71f84b-b6dc-4f7c-b27a-0e0ec496e0b9: Prijs # Prijs
    1d47ddfe-72ec-4111-b1cd-3caa343d172b: Logo # Logo
    03c0ccce-3c8f-4b90-b67e-5f599166b630: stickerCategory # stickerCategory
    4a826233-2673-4533-bdf4-5dd6f0487adc: Illustrashop # Illustrashop
    5a45df4e-9a9d-4d13-9a73-62265aafe1d4: Fotos # Fotos
    5e28166a-2ab1-46bb-8328-368e476cf417: 'Stickers Overview' # Stickers Overview
    6a400ca0-3ee3-4d75-8e6c-34fb5c2438bb: stickerCategory # stickerCategory
    6f2b4685-b2b6-4e96-94e0-958af07acb19: stickers # stickers
    8f72d8fc-c020-40aa-a013-0550c3735702: cardImage # cardImage
    56a88afc-1100-4ee0-8f36-380a2e7fdc28: 'Public Schema' # Public Schema
    269e7b2c-b1d6-4d4f-9fa1-eb0e7505e651: stock # stock
    1279f5c0-f5c7-4b61-beea-a683143f92b6: stickerCategory # stickerCategory
    86945d3a-9e49-4245-b5cf-e27ed83e8f76: Images # Images
    324648bc-f878-478b-804e-1e657b33c79d: aboutDescription # aboutDescription
    347620c5-2d4f-42f5-8745-b16fff55dec6: Home # Home
    67215269-f89c-4e18-afb6-1bd0c79a3280: productBeschrijving # productBeschrijving
    a7e94ab7-815d-4e39-be33-9d713992d759: cardDescription # cardDescription
    b3de9e6b-9d6f-49b1-acac-90c18bdbd2c2: cardPrice # cardPrice
    b983c117-aebe-4dd5-92b8-5d0d49b48b82: Illustrashop # Illustrashop
    cfac5752-0197-4073-aff8-92bc90f7c127: siteLogo # siteLogo
    cfbedfb0-7790-41c9-a3cc-0f9f7cdb7227: stickers # stickers
    dc56cc87-678f-4d74-a517-414aba78a3b2: About # About
    ddfe4e50-9930-4426-8745-eccf0d51b848: 'Stickers Overview' # Stickers Overview
    f3e5a5c7-e072-47da-845f-69c01d2a16a0: VAT # VAT
    f71a819e-0877-407a-a17a-b82f88e5e2c0: aboutTitle # aboutTitle
    f353af18-96fc-4a3f-9c95-586303d02d2c: Home # Home
    fdb40e6b-86d1-45a0-9ff2-85269d1d1550: About # About
system:
  edition: solo
  live: true
  name: Illustrashop
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
