defaultPlacement: end
enableVersioning: true
entryTypes:
  - 3f297f3c-4b68-451d-840e-97f9cc710f6d # contact
handle: contact
maxAuthors: 1
name: contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4a826233-2673-4533-bdf4-5dd6f0487adc: # Illustrashop
    enabledByDefault: true
    hasUrls: true
    template: _contact/_contact.twig
    uriFormat: contact
type: single
