defaultPlacement: end
enableVersioning: true
entryTypes:
  - f353af18-96fc-4a3f-9c95-586303d02d2c # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4a826233-2673-4533-bdf4-5dd6f0487adc: # Illustrashop
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
  bd303dcd-4fa3-453e-9981-fcc3995d5a89: # IllustrashopNL
    enabledByDefault: true
    hasUrls: true
    template: _Nederlands/index.twig
    uriFormat: __home__
type: single
