defaultPlacement: end
enableVersioning: true
entryTypes:
  - 99b402a4-fa5c-47f6-bafb-92595991104c # newPage
handle: newpage
maxAuthors: 1
name: newPage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4a826233-2673-4533-bdf4-5dd6f0487adc: # Illustrashop
    enabledByDefault: true
    hasUrls: true
    template: newPage/_entry
    uriFormat: 'newpage/{slug}'
  bd303dcd-4fa3-453e-9981-fcc3995d5a89: # IllustrashopNL
    enabledByDefault: true
    hasUrls: true
    template: newPage/_entry
    uriFormat: 'newpage/{slug}'
type: channel
