defaultPlacement: end
enableVersioning: true
entryTypes:
  - 6f2b4685-b2b6-4e96-94e0-958af07acb19 # stickers
handle: stickers
maxAuthors: 1
name: stickers
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4a826233-2673-4533-bdf4-5dd6f0487adc: # Illustrashop
    enabledByDefault: true
    hasUrls: true
    template: _stickers/_entry
    uriFormat: 'our-stickers/{slug}'
  bd303dcd-4fa3-453e-9981-fcc3995d5a89: # IllustrashopNL
    enabledByDefault: true
    hasUrls: true
    template: _stickers/_entry
    uriFormat: 'onze-stickers/{slug}'
structure:
  maxLevels: null
  uid: 7ef3b58e-35ac-4faa-ac93-bdab7e292367
type: structure
