defaultPlacement: end
enableVersioning: true
entryTypes:
  - 5e28166a-2ab1-46bb-8328-368e476cf417 # Stickers Overview
handle: stickersOverview
maxAuthors: 1
name: 'Stickers Overview'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4a826233-2673-4533-bdf4-5dd6f0487adc: # Illustrashop
    enabledByDefault: true
    hasUrls: true
    template: _stickers/_overview.twig
    uriFormat: our-stickers
type: single
